# Default values for webportal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ibmcase/casewebportal 
  tag: latest
  pullPolicy: Always
service:
  name: webportalsvc
  type: ClusterIP
  externalPort: 6100
  internalPort: 6100
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - portal.brown.case
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

config:
  secureGateway:
    url: https://cap-sg-prd-5.integration.ibmcloud.com:16582
  apiGateway:
    hostUrl: https://172.16.50.8
    url: /csplab/sb/iib-inventory-api
    clientid: 59a3a4cb-db42-40ff-bf22-b8c3b5e9eedb
  conversationBroker:
    url: https://wcsbroker.cyan.case/api/conversation
  advisorBroker:
    url: https://wcsbroker.cyan.case/api/advisor
  customerAPI:
    url: http://172.16.40.131/caseserv/api
    host: customer.green.case
  mode: cyan
  environment: private
  port: 6100
  version: 0.0.7

resources:
  limits:
    cpu: 100m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 512Mi
